### ISSUE TITLE
Xcode 8. "No Info.plist file in application bundle or no NSPrincipalClass in the Info.plist file, existing" error

### ISSUE THREAD

**Issue by NikolayShubenkov** [onmyway133/XcodeWay#16]
Hello. I try to run your project from Xcode but it is got terminated immediately due to this error in xcode:

Info.plist file in application bundle or no NSPrincipalClass in the Info.plist file

Could you fix this, please?
Due to this error extension is not get install correctly. No new menu Item showed and after I enable this extension Xcode starts working very slow.

**Comment by onmyway133** [comment]
@NikolayShubenkovProgSchool Hi, I don't get this issue. I only get that the `identifier` contains some spaces (which was allowed before), which I just fix. Can you checkout `master` again?
