### ISSUE TITLE
do not have permission to open

### ISSUE THREAD

**Issue by cuong1112035** [onmyway133/XcodeWay#18]
Hello

Thanks for your tutorial and XcodeWay. I tried to use your extension but it showed me an error 
<img width="443" alt="screen shot 2017-09-11 at 9 21 42 pm" src="https://user-images.githubusercontent.com/6124016/30279493-8b80eb78-9737-11e7-86e4-111c759c15be.png">
Could you please help me to fix it?

**Comment by onmyway133** [comment]
@cuong1112035 Hi, thanks checking out. What version of Xcode do you use?

**Comment by cuong1112035** [comment]
@onmyway133  I am using Version 8.3.3

**Comment by onmyway133** [comment]
@cuong1112035 thanks. I will fix that together with Xcode 9 release, because Xcode 8 has problem debugging the extension.

**Comment by onmyway133** [comment]
@cuong1112035 Hi, I'm rewriting XcodeWay, it will be more fantastic. Will ping you when new version comes out

**Comment by cuong1112035** [comment]
hi @onmyway133 
I am looking forward to see it. I want to help you to code but I have no experience in mac OS development. But I am willing to help you to test it as a user. 
Thanks

**Comment by onmyway133** [comment]
@cuong1112035 Hi, you can now check version 2.0.0 https://github.com/onmyway133/XcodeWay/releases/tag/2.0.0, follow the README to install
