### ISSUE TITLE
Support Xcode 6 simulator document location

### ISSUE THREAD

**Issue by veiz** [onmyway133/XcodeWay#2]
Xcode 6 moved document location for simulator from old _~/Library/Application Support/IPhone Simulator/_ to **/Users/{YOUR NAME}/Library/Developer/CoreSimulator/Devices/{DEVICE ID}/data/Containers/Data/Application/{APPLICATION ID}/**

Check http://stackoverflow.com/a/26014275.

**Comment by onmyway133** [comment]
@veiz thanks for letting me know. I just fixed it https://github.com/onmyway133/XcodeWay/commit/7a97ca13cad0e8b30b05d7f4e2a6e5cb41c5edc1

The trick is find the latest folder to show, inspired by this https://nsrover.wordpress.com/2014/11/28/ios8-simulator-documents-directory/
